project_id = "bacqgdjiarwkgkwiqgpa"

[auth]
site_url = "https://lasalle360.vercel.app"
additional_redirect_urls = [
  "https://lasalle360.vercel.app",
  "https://lasalle360.vercel.app/**"
]

[functions.create-user]
verify_jwt = true

[functions.send-consolidated-booking-email]
verify_jwt = false
