// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bacqgdjiarwkgkwiqgpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhY3FnZGppYXJ3a2drd2lxZ3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTM4ODgsImV4cCI6MjA3NDQ2OTg4OH0.GFyN2Sx-V0Qmsw-Tx1q5oAYTtJqSs-0ED8MVkV8_6X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});